version: "3"
services:
  
  reverse:
    container_name: reverse
    image: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumnes:
      ./server_config/nginx_config:/etc/nginx
      ./server_config/SSL:/etc/ssl/private
    depends_on:
      - flask-app

  flask-app:
    container_name: flask-app
    restart: always
    build: ./app
    ports:
      - 3000:3000
    depends_on:
      - mongo-server
    
  mongo-server:
    container_name: mongo_server
    restart: always
    image: mongo
    volumes:
      - ./mongo_data:/data/db
    ports:
      - 27017:27017